version: '3.0'
services:      
  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
     - 3310:3306

  api-clusters-db:
    container_name: api-clusters-db
    image: redis:alpine
    restart: always
    ports:
     - 6079:6379

  api-clusters-zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    container_name: api-clusters-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
     
  api-pricing-db:
    container_name: api-pricing-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_pricing'
      MYSQL_ROOT_PASSWORD: 'muppet'        
    ports:
     - 3311:3306
